<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    const getPokemonAjax = async () => {
      try {
        /**
          예외 처리는 실행하려고 하는 코드를 try 블록으로 감싸고,
          오류가 발생하면 catch 블록에서 오류를 처리하는 방식으로 진행하는 비교적 간단한 방식입니다.
          '예외가 발생하는' 상황이 무엇인지, 어떤 오류가 발생하는지, 어떻게처리해야 하는지 등을 미리 알 수 없는 경우에 사용하는데, 개발자의 '실수'가 아닌 영역도 존재합니다.
          예를 들어, 네트워크 요청을 보내는 과정에서 네트워크가 끊어지거나, 서버가 다운되는 등의 상황이 발생할 수 있기 때문에 네트워크 통신 불량은 '개발자'의 실수가 아닌 '예외'로 처리해야 합니다.

          예를 들어 통신이 원활하지 않아 아래의 AJAX 통신이 실패할 경우
          '현재 통신이 불량입니다.' 라는 메세지를 사용자에게 전달하는 것도 예외처리의 일환입니다.

          예상하지 못하거나, 예상할 수 없는 상황에 따른 다방면의 상황을 대비하기 위해서
          '등장해야만 하는 것'에 초점을 맞추어 예외처리를 진행합니다.
        */ 

        // 첫 번째 요청: 전체 포켓몬 수 가져오기
        const response = await fetch("https://pokeapi.co/api/v2/pokemon/");
        const data = await reponse.json();
        const count = data.count;

        // 각 포켓몬이 정보를 가져오기 위한 요청
        for (let i = 1; i <= count; i++) {
          const pokemonResponse = await fetch(`https://pokeapi.co/api/v2/pokemon/${i}/`);
          const pokemonData = await pokemonResponse.json();
          
          // species의 name 출력
          // 하나씩 이름이 통신을 받아 출력되는 것을 확인할 수 있으며,
          // 네트워크 탭에서 어떤 일이 벌어지는지 확인해보는 과정을 통해서 비동기 통신의 흐름을 이해할 수 있습니다.
          console.log(pokemonData.species.name);
        }
      }
    }
  </script>
</body>
</html>